import type { CredentialTypeDefinition } from "./types";

export const builtinCredentialTypes: CredentialTypeDefinition[] = [
  {
    id: "bearer",
    name: "Bearer Token",
    description: "Generic bearer token authentication",
    authType: "bearer",
    category: "generic",
    fields: [
      {
        name: "token",
        type: "string",
        label: "Token",
        required: true,
        sensitive: true,
        description: "Bearer token value",
      },
    ],
  },
  {
    id: "api_key",
    name: "API Key",
    description: "Generic API key authentication",
    authType: "api_key",
    category: "generic",
    fields: [
      {
        name: "key",
        type: "string",
        label: "API Key",
        required: true,
        sensitive: true,
      },
      {
        name: "headerName",
        type: "string",
        label: "Header Name",
        required: false,
        sensitive: false,
        description: "Header to send the key in (default: X-API-Key)",
        placeholder: "X-API-Key",
      },
    ],
  },
  {
    id: "basic_auth",
    name: "Basic Auth",
    description: "HTTP Basic Authentication",
    authType: "basic_auth",
    category: "generic",
    fields: [
      {
        name: "username",
        type: "string",
        label: "Username",
        required: true,
        sensitive: false,
      },
      {
        name: "password",
        type: "string",
        label: "Password",
        required: true,
        sensitive: true,
      },
    ],
  },
  {
    id: "oauth2",
    name: "OAuth2",
    description: "Generic OAuth2 credentials",
    authType: "oauth2",
    category: "generic",
    fields: [
      {
        name: "clientId",
        type: "string",
        label: "Client ID",
        required: true,
        sensitive: false,
      },
      {
        name: "clientSecret",
        type: "string",
        label: "Client Secret",
        required: true,
        sensitive: true,
      },
      {
        name: "accessToken",
        type: "string",
        label: "Access Token",
        required: false,
        sensitive: true,
      },
      {
        name: "refreshToken",
        type: "string",
        label: "Refresh Token",
        required: false,
        sensitive: true,
      },
      {
        name: "tokenUrl",
        type: "string",
        label: "Token URL",
        required: true,
        sensitive: false,
        placeholder: "https://example.com/oauth/token",
      },
      {
        name: "scope",
        type: "string",
        label: "Scopes",
        required: false,
        sensitive: false,
      },
    ],
  },
  {
    id: "github",
    name: "GitHub",
    description: "GitHub personal access token",
    authType: "bearer",
    category: "developer",
    fields: [
      {
        name: "token",
        type: "string",
        label: "Personal Access Token",
        required: true,
        sensitive: true,
        description: "Classic or fine-grained PAT",
        regex: "^(ghp_|github_pat_)",
      },
    ],
    testEndpoint: {
      url: "https://api.github.com/user",
      method: "GET",
      headerTemplate: { Authorization: "Bearer {{token}}" },
    },
  },
  {
    id: "slack",
    name: "Slack",
    description: "Slack Bot or Webhook credentials",
    authType: "bearer",
    category: "communication",
    fields: [
      {
        name: "botToken",
        type: "string",
        label: "Bot Token",
        required: false,
        sensitive: true,
        regex: "^xoxb-",
      },
      {
        name: "webhookUrl",
        type: "string",
        label: "Webhook URL",
        required: false,
        sensitive: true,
        placeholder: "https://hooks.slack.com/services/...",
      },
    ],
  },
  {
    id: "discord",
    name: "Discord",
    description: "Discord webhook or bot token",
    authType: "custom",
    category: "communication",
    fields: [
      {
        name: "webhookUrl",
        type: "string",
        label: "Webhook URL",
        required: false,
        sensitive: true,
      },
      {
        name: "botToken",
        type: "string",
        label: "Bot Token",
        required: false,
        sensitive: true,
      },
    ],
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Stripe API credentials",
    authType: "bearer",
    category: "payment",
    fields: [
      {
        name: "secretKey",
        type: "string",
        label: "Secret Key",
        required: true,
        sensitive: true,
        regex: "^sk_",
      },
      {
        name: "webhookSecret",
        type: "string",
        label: "Webhook Secret",
        required: false,
        sensitive: true,
        regex: "^whsec_",
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "OpenAI API key",
    authType: "bearer",
    category: "ai",
    fields: [
      {
        name: "apiKey",
        type: "string",
        label: "API Key",
        required: true,
        sensitive: true,
        regex: "^sk-",
      },
      {
        name: "organization",
        type: "string",
        label: "Organization ID",
        required: false,
        sensitive: false,
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Anthropic API key",
    authType: "api_key",
    category: "ai",
    fields: [
      {
        name: "apiKey",
        type: "string",
        label: "API Key",
        required: true,
        sensitive: true,
        regex: "^sk-ant-",
      },
    ],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "LinkedIn API credentials",
    authType: "oauth2",
    category: "social",
    fields: [
      {
        name: "accessToken",
        type: "string",
        label: "Access Token",
        required: true,
        sensitive: true,
      },
      {
        name: "personUrn",
        type: "string",
        label: "Person URN",
        required: true,
        sensitive: false,
        placeholder: "urn:li:person:abc123",
      },
      {
        name: "clientId",
        type: "string",
        label: "Client ID",
        required: false,
        sensitive: false,
      },
      {
        name: "clientSecret",
        type: "string",
        label: "Client Secret",
        required: false,
        sensitive: true,
      },
      {
        name: "refreshToken",
        type: "string",
        label: "Refresh Token",
        required: false,
        sensitive: true,
      },
    ],
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "SendGrid email API",
    authType: "bearer",
    category: "communication",
    fields: [
      {
        name: "apiKey",
        type: "string",
        label: "API Key",
        required: true,
        sensitive: true,
        regex: "^SG\\.",
      },
    ],
  },
  {
    id: "aws",
    name: "AWS",
    description: "Amazon Web Services credentials",
    authType: "custom",
    category: "cloud",
    fields: [
      {
        name: "accessKeyId",
        type: "string",
        label: "Access Key ID",
        required: true,
        sensitive: false,
      },
      {
        name: "secretAccessKey",
        type: "string",
        label: "Secret Access Key",
        required: true,
        sensitive: true,
      },
      {
        name: "region",
        type: "string",
        label: "Region",
        required: false,
        sensitive: false,
        placeholder: "us-east-1",
      },
    ],
  },
  {
    id: "custom",
    name: "Custom",
    description: "Custom key-value credential",
    authType: "custom",
    category: "generic",
    fields: [],
  },
];
